nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: 
            - '^https://demo\.nakedcode\.es$'
            - '%env(string:CORS_ALLOW_ORIGIN)%'
            - '^http://localhost:[0-9]+$'
            - '^http://127\.0\.0\.1:[0-9]+$'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: 
                - '^https://demo\.nakedcode\.es$'
                - '%env(string:CORS_ALLOW_ORIGIN)%'
                - '^http://localhost:[0-9]+$'
                - '^http://127\.0\.0\.1:[0-9]+$'
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
            allow_credentials: true
